name: Docker Publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Get or create version
      id: get_version
      run: |
        if [ ! -f .version ]; then
          echo "::set-output name=version::0"
        else
          echo "::set-output name=version::$(cat .version)"
        fi
    
    - name: Bump version
      id: bump_version
      run: |
        current_version=${{ steps.get_version.outputs.version }}
        new_version=$((current_version + 1))
        echo $new_version > .version
        echo "::set-output name=new_version::v$new_version"
    
    - name: Commit version bump
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .version
        git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}"
        git push
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/ai-proxy:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/ai-proxy:${{ steps.bump_version.outputs.new_version }}
