name: Docker Publish

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Get or create version
      id: get_version
      run: |
        if [ ! -f .version ]; then
          echo "version=0" >> $GITHUB_OUTPUT
        else
          echo "version=$(cat .version)" >> $GITHUB_OUTPUT
        fi
    
    - name: Bump version
      id: bump_version
      run: |
        current_version=${{ steps.get_version.outputs.version }}
        new_version=$((current_version + 1))
        echo $new_version > .version
        echo "new_version=v$new_version" >> $GITHUB_OUTPUT
    
    - name: Commit version bump
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .version
        git commit -m "Bump version to ${{ steps.bump_version.outputs.new_version }}"
        git push
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/ai-proxy:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/ai-proxy:${{ steps.bump_version.outputs.new_version }}
